### ISSUE TITLE
bug: import fail, _jaroWinkler.jaroWinkler is not a function (it is undefined)

### ISSUE THREAD

**Issue by ivolucien** [skyra-project/jaro-winkler#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

This is in the context of writing an expo (51.0.37) react-native (0.75.4) app with node v20. I have not tested it outside that context.

I get the following error when I import this module as suggested and try to use the function:

```
import { jaroWinkler } from '@skyra/jaro-winkler';

const result = jaroWinkler('foo', 'bar');
// TypeError: 0, _jaroWinkler.jaroWinkler is not a function (it is undefined)
```

**This is just an FYI**, I've already switched to https://github.com/jordanthomas/jaro-winkler

### Steps To Reproduce

See description

### Expected behavior

`result` should have a number between 0 and 1 assigned

**Comment by favna** [comment]
This should be reported to Expo, or rather [Metro Bundler](https://metrobundler.dev) which they use for bundling. This package conforms to the modern setup of configuring a package for CJS, ESM and web and ships a proper cross-platform compatible bundle. Ironically unlike jordnathomas' package which ships CJS exclusively which is technically not even web app compatible without compatibility layers provided by the bundler, as opposed to an ESM bundle which is natively web compatible. If Metro Bundler doesn't support a modern setup, that's on Metro to solve. @skyra/jaro-winkler will work perfectly fine with bundlers like Vite, Webpack, Parcel, Rollup, Rolldown, Snowpack, and Esbuild so our setup is not to blame here for sure.

Furthermore, seeing as the type error says `_jaroWinkler.jaroWinkler` that makes me think that Metro thinks this package is a CJS package as it doesn't directly import the ESM function (it gets namespaced as is common with CJS). If that is true then I have a feeling that Metro doesn't properly read `.exports.imports.default` in the `package.json`, nor `.module` and just automatically assumes a package to be CJS, possibly because `.type` is not set to `module`, which would be a wrong assumption.
